// <auto-generated />
using System;
using Detara.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Detara.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(DetaraDbContext))]
    partial class DetaraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Detara.Domain.Agenda.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteNomeSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuracaoPlanejadaMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacaoInterna")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ObservacaoSolicitante")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("VeiculoDescricaoSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VeiculoPlacaSnapshot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ClienteId");

                    b.HasIndex("EmpresaId", "InicioUtc");

                    b.HasIndex("EmpresaId", "VeiculoId");

                    b.HasIndex("EmpresaId", "Status", "InicioUtc");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Agenda.AgendamentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DuracaoReferenciaMinutosSnapshot")
                        .HasColumnType("int");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemCatalogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoReferenciaSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TipoPrecificacaoSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasAlternateKey("EmpresaId", "Id");

                    b.HasIndex("EmpresaId", "AgendamentoId", "Ordem")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "TipoItem", "ItemCatalogoId");

                    b.HasIndex("EmpresaId", "AgendamentoId", "TipoItem", "ItemCatalogoId")
                        .IsUnique();

                    b.ToTable("AgendamentosItens", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.CategoriaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "EhAtivo");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("CategoriasServico", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CpfCnpj")
                        .IsUnique()
                        .HasFilter("[CpfCnpj] IS NOT NULL");

                    b.HasIndex("EmpresaId", "Nome");

                    b.HasIndex("EmpresaId", "Telefone");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("America/Sao_Paulo");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Pacote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal?>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPrecificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "EhAtivo");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("Pacotes", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.PacoteServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("PacoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ServicoId");

                    b.HasIndex("EmpresaId", "PacoteId", "Ordem");

                    b.HasIndex("EmpresaId", "PacoteId", "ServicoId")
                        .IsUnique();

                    b.ToTable("PacotesServicos", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissoes", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CategoriaServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DuracaoEstimadaMinutos")
                        .HasColumnType("int");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPrecificacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CategoriaServicoId");

                    b.HasIndex("EmpresaId", "EhAtivo");

                    b.HasIndex("EmpresaId", "CategoriaServicoId", "Nome")
                        .IsUnique();

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "PerfilId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.UsuarioPaginaFavorita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Pagina")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("UsuarioPreferenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "UsuarioPreferenciaId", "Ordem");

                    b.HasIndex("EmpresaId", "UsuarioPreferenciaId", "Pagina")
                        .IsUnique();

                    b.ToTable("UsuariosPaginasFavoritas", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.UsuarioPreferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PaginaInicial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("SidebarRecolhida")
                        .HasColumnType("bit");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("UsuariosPreferencias", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoModelo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhAtivo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<string>("Versao")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ClienteId");

                    b.HasIndex("EmpresaId", "Placa")
                        .IsUnique();

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("PerfilPermissao", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfisPermissoes", (string)null);
                });

            modelBuilder.Entity("Detara.Domain.Agenda.Agendamento", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Agenda.AgendamentoItem", b =>
                {
                    b.HasOne("Detara.Domain.Agenda.Agendamento", "Agendamento")
                        .WithMany("Itens")
                        .HasForeignKey("EmpresaId", "AgendamentoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.CategoriaServico", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Cliente", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Pacote", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.PacoteServico", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.Pacote", "Pacote")
                        .WithMany("Servicos")
                        .HasForeignKey("EmpresaId", "PacoteId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.Servico", "Servico")
                        .WithMany("Pacotes")
                        .HasForeignKey("EmpresaId", "ServicoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacote");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Perfil", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Servico", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.CategoriaServico", "CategoriaServico")
                        .WithMany("Servicos")
                        .HasForeignKey("EmpresaId", "CategoriaServicoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaServico");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("EmpresaId", "PerfilId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.UsuarioPaginaFavorita", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.UsuarioPreferencia", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId", "UsuarioPreferenciaId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.UsuarioPreferencia", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Detara.Domain.Entidades.UsuarioPreferencia", "EmpresaId", "UsuarioId")
                        .HasPrincipalKey("Detara.Domain.Entidades.Usuario", "EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Veiculo", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("EmpresaId", "ClienteId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PerfilPermissao", b =>
                {
                    b.HasOne("Detara.Domain.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Detara.Domain.Entidades.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Detara.Domain.Agenda.Agendamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.CategoriaServico", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Pacote", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Detara.Domain.Entidades.Servico", b =>
                {
                    b.Navigation("Pacotes");
                });
#pragma warning restore 612, 618
        }
    }
}
